image_size: 224
vit: "B/32"
vit_grad_ckpt: True
vit_ckpt_layer: 12
init_lr: 3e-4
min_lr: 1e-6
weight_decay: 1e-2
max_epoch: 10
batch_size: 64

dataset:
  name: "your_dataset_name"
  root_dir: "/path/to/your/dataset"
  train_split: "train"
  val_split: "val"

training:
  num_workers: 4
  pin_memory: True
  shuffle: True

validation:
  batch_size: 64
  num_workers: 4
  pin_memory: True

wandb:
  project: "Tag2Text"
  entity: "your_wandb_entity" # Optional, only if you are part of a specific team/entity on WandB
  log_interval: 10
